(defun midje-random-praise ()
  (concat (nth (mod (random t) (length midje-praise-quotes))
	       midje-praise-quotes )
	  "\n"))

(defvar midje-praise-quotes 
'(
  "Every time I learn something new, it pushes out something old! -- Homer"
  "Okay, brain. You don't like me, and I don't like you, but let's get through this thing and then I can continue killing you with beer. -- Homer"
  "Bart, a woman is like a beer. They look good, they smell good, and you'd step over your own mother just to get one! -- Homer"
  "Oh, yeah, what are you gonna do? Release the dogs? Or the bees? Or the dogs with bees in their mouth and when they bark, they shoot bees at you? -- Homer"
  "Donuts. Is there anything they can’t do? -- Homer"
  "English? Who needs that? I’m never going to England. -- Homer"
  "Everybody makes mistakes. That’s why they put erasers on pencils. -- Homer"
  "Everything looks bad if you remember it. -- Homer"
  "Facts are meaningless. You could use facts to prove anything that’s even remotely true! -- Homer"
  "Here’s to alcohol, the cause of - and solution to - all life’s problems. -- Homer"
  "I never apologize, I’m sorry but that’s the way I am. -- Homer"
  "I think I’ve figured this balloon thing out, Marge. It can go up and down, but not side to side or back in time. -- Homer"
  "I want the answers now or eventually! -- Homer"
  "I want to share something with you: The three little sentences that will get you through life. Number 1: Cover for me. Number 2: Oh, good idea, Boss! Number 3: It was like that when I got here. -- Homer"
  "I was working on a flat tax proposal and accidentally proved there was no God. -- Homer"
  "I wish God were alive to see this. -- Homer"
  "I’ve learned that life is one crushing defeat after another until you just wish Flanders was dead. -- Homer"
  "I’ve gone back in time to when dinosaurs weren’t just confined to zoos. -- Homer"
  "It’s like the story of David and Goliath, except this time David won. -- Homer"
  "Internet. They have that on computers now? -- Homer"
  "Oh, spiteful one! Tell me who to smote and they shall be smotted. -- Homer"
  "Stupidity got us into this mess, and stupidity will get us out. -- Homer"
  "Listen, strange women lying in ponds distributing swords is no basis for a system of government... -- Dennis (Holy Grail)"
  "You can’t expect to wield supreme executive power just ‘cause some watery tart threw a sword at you! -- Dennis (Holy Grail)"
  "Oh, what sad times are these when passing ruffians can ‘ni’ at will to old ladies. There is a pestilence upon this land. Nothing is sacred. -- Roger the Shrubber (Holy Grail)"
  "So, you think you could out-clever us French folk with your silly knees-bent running about advancing behavior?! -- French Guard (Holy Grail)"
  "Please! This is supposed to be a happy occasion. Let’s not bicker and argue over who killed who. -- King of Swamp Castle (Holy Grail)"
  "NOBODY expects the Spanish Inquisition! Our chief weapon is surprise…surprise and fear…fear and surprise…. Our two weapons are fear and surprise…and ruthless efficiency... -- Monty Python")
)

(provide 'midje-mode-praise)


;; '(
;;   "When someone asks you if you're a god, you say 'YES'! -- Zeddemore" 
;;   "The work itself praises the master. -- CPE Bach"
;;   "Happiness comes when you believe that you have done something truly meaningful. -- Yan"
;;   "I do believe in praising that which deserves to be praised. -- Dean Smith"
;;   "Out of clutter find simplicity; from discord find harmony; in the middle of difficulty lies opportunity. -- Einstein"
;;   "Satisfaction lies in the effort, not in the attainment, full effort is full victory. -- Gandhi"
;;   "One of the symptoms of an approaching nervous breakdown is the belief that one's work is terribly important. -- Russell"
;;   "The sum of wisdom is that time is never lost that is devoted to work. -- Emerson"
;;   "Without work, all life goes rotten. -- Camus"
;;   "Work joyfully and peacefully, knowing that right thoughts and right efforts will inevitably bring about right results. -- Allen"
;;   "Work is either fun or drudgery. It depends on your attitude. I like fun. -- Barrett"
;;   "There's a certain satisfaction in a little bit of pain. -- Madonna"
;;   "One small test for a codebase, one giant leap for quality kind! -- @zspencer"
;;   "Hey! You're green! Refactor then we get to go red again! -- @zspencer"
;;   "Woohoo! -- @zspencer"
;;   "Ding! You Have Gained Experience -- @zspencer"
;;   "A journey of a thousand miles begins with a single step. -- @alanmstokes"
;;   "If this isn't nice, I don't know what is. -- Vonnegut"
;;   "Simplicity, carried to the extreme, becomes elegance. -- Jon Franklin"
;;   "This is the future you were hoping for. -- @Vaguery"
;;   "O frabjous day! Callooh! Callay! -- Lewis Carroll"
;;   "Whoever wants to reach a distant goal must take small steps. -- fortune cookie"
;;   "The next function taunts you still. Will you rise to the challenge? -- anonymous"
;;   "Any intelligent fool can make things bigger, more complex, and more violent. It takes a touch of genius -- and a lot of courage -- to move in the opposite direction. -- Schumacher"
;;   "Excellence is not an act but a habit. -- Aristotle"
;;   "Code you'd be proud to give your mom to show off on the fridge. -- Mike Cohn"
;;   "A clean boundary between useful abstractions and the grubby code that touches the real world is always a good thing. -- Ron Jeffries"
;;   "Of course the universe *is* out to get us, but it's not going to do it by passing a null to one of our methods. -- Ron Jeffries"
;;   "Good code is its own best documentation. -- Steve McConnell"
;;   "First they ignored you, then they laughed at you, then they fought you, now you've won. -- Not quite Gandhi"
;;   "The reward of a thing well done is to have done it. -- Emerson"
;;   "The highest reward for a man's toil is not what he gets for it but what he becomes by it. -- Ruskin"
;;   "Before the reward there must be labor. You plant before you harvest. You sow in tears before you reap joy. -- Ransom"
;;   "Intellectual 'work' is misnamed; it is a pleasure, a dissipation, and is its own highest reward. -- Twain"
;;   "The biggest reward for a thing well done is to have done it. -- Voltaire"
;;   "Effort only fully releases its reward after a person refuses to quit. -- Hill"
;;   "The journey is the reward. -- traditional"
;;   "For every disciplined effort, there is a multiple reward. -- Rohn"
;;   "Happiness is not a reward / it is a consequence. -- Ingersoll"
;;   "It takes time to succeed because success is merely the natural reward of taking time to do anything well. -- Ross"
;;   "There is an inevitable reward for good deeds. -- Ming Fu Wu"
;;   "Achievement is its own reward. -- David Lynch"
;;   "Not in rewards, but in the strength to strive, the blessing lies. -- Towbridge"
;;   "The right word may be effective, but no word was ever as effective as a rightly timed pause. -- Twain"
;; )
